blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('blogs/', views.BlogPostListView.as_view(), name='blogposts'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blogs/<int:pk>', views.BlogPostDetailView.as_view(), name='blogpost-detail'),
    path('bloggers/<int:pk>', views.BloggerDetailView.as_view(), name='blogger-detail'),
    path('blogs/<int:pk>/create', views.blogpost_add_comment, name='blogpost-comment'),
]

diyblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='blog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Blogger(models.Model):
    """Model representing an author"""
    username = models.CharField(max_length=100)
    bio = models.TextField(max_length=1000, help_text='Enter a brief description of the blogger')

    def __str__(self):
        """String for representing the Model object"""
        return f'{self.username}'

    def get_absolute_url(self):
        """Returns the url to access a particular blogger instance"""
        return reverse('blogger-detail', args=[str(self.id)])


class BlogPost(models.Model):
    """Model representing a blog post"""
    title = models.CharField(max_length=200)
    post_date = models.DateField()
    author = models.ForeignKey(Blogger, on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=1000, help_text="Enter the text of the blog post")

    def __str__(self):
        """String for representing the Model object"""
        return f'{self.title} - {self.author}'

    def get_absolute_url(self):
        """Returns the url to access a particular blogpost instance"""
        return reverse('blogpost-detail', args=[str(self.id)])


class Comment(models.Model):
    blogpost = models.ForeignKey(BlogPost, on_delete=models.SET_NULL, null=True)
    post_time = models.DateTimeField()
    commenter = models.CharField(max_length=100, help_text="Enter your name")
    text = models.TextField(max_length=1000, help_text="Enter your comment")

    def __str__(self):
        """String for representing the Model object"""
        return self.text[:75]

blog/forms.py
import datetime
from django import forms


class NewCommentForm(forms.Form):
    """Form for adding new comments"""
    comment_text = forms.CharField(max_length=1000, help_text="Enter your comment", widget=forms.Textarea)

    def clean_comment_text(self):
        data =  self.cleaned_data['comment_text']
        return data

blog/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic

from blog.models import Blogger, BlogPost, Comment
from blog.forms import NewCommentForm

# Create your views here.
def home(request):
    """View function for home page of site"""
    num_bloggers = Blogger.objects.count()
    num_blogposts = BlogPost.objects.count()
    num_comments = Comment.objects.count()

    context = {
        'num_bloggers': num_bloggers,
        'num_blogposts': num_blogposts,
        'num_comments': num_comments,
    }

    return render(request, 'home.html', context=context)


class BlogPostListView(generic.ListView):
    model = BlogPost
    paginate_by = 5
    queryset = BlogPost.objects.all().order_by('-post_date')


class BloggerListView(generic.ListView):
    model = Blogger
    paginate_by = 5
    queryset = Blogger.objects.all().order_by('username')


class BlogPostDetailView(generic.DetailView):
    model = BlogPost


class BloggerDetailView(generic.DetailView):
    model = Blogger


@login_required
def blogpost_add_comment(request, pk):
    blogpost = get_object_or_404(BlogPost, pk=pk)

    # If this is a POST request, process the Form data
    if request.method == 'POST':
        form = NewCommentForm(request.POST)
        if form.is_valid():
            blogpost.comment_set.create(blogpost=blogpost, post_time=datetime.datetime.now(),
                                        commenter=request.user, text=form.cleaned_data['comment_text'])
            return HttpResponseRedirect(reverse('blogpost-detail', kwargs={'pk': pk}))
    else:
        form = NewCommentForm()

    context = {
        'form': form,
        'blogpost': blogpost,
    }

    return render(request, 'blog/add_comment.html', context)

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>DIY BLOG</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'blogposts' %}">All blog posts</a></li>
          <li><a href="{% url 'bloggers' %}">All bloggers</a></li>
        {% if user.is_authenticated %}
          <li>User: {{ user.get_username }}</li>
          <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% endif %}
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
      {% block pagination %}
        {% if is_paginated %}
          <div class="pagination">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
              </span>
          </div>
        {% endif %}
    {% endblock %}
    </div>
  </div>
</body>
</html>

blog/templates/blog/add_comment.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blog post: {{ blogpost.title }}</h1>
<p><a href="{{ blogpost.get_absolute_url }}">Return to post</a></p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

blog/templates/blog/blogger_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blogger: {{ blogger.username }}</h1>
  <div style="margin-left:20px;margin-top:20px">
      <h4>Bio</h4>
      <p>{{ blogger.bio }}</p>
      <h4>Blogs list</h4>
      <ul>
        {% for blogpost in blogger.blogpost_set.all reversed %}
        <li><a href="{{ blogpost.get_absolute_url }}">{{ blogpost.title }}</a> ({{ blogpost.post_date }})</li>
        {% endfor %}
      </ul>
  </div>
{% endblock %}

blog/templates/blog/blogger_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blogger List</h1>
  {% if blogger_list %}
  <ul>
    {% for blogger in blogger_list %}
      <li>
        <a href="{{ blogger.get_absolute_url }}">{{ blogger.username }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no bloggers on the blog.</p>
  {% endif %}
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ blogpost.title }}</h1>


  <p><strong>Post date</strong> {{ blogpost.post_date }}</p>
  <p><strong>Author:</strong> <a href="{% url 'blogger-detail' blogpost.author.pk %}">{{ blogpost.author }}</a></p>
  <p><strong>Description:</strong> {{ blogpost.description }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Comments</h4>

  {% if blogpost.comment_set.all %}
    {% for comment in blogpost.comment_set.all %}
      <hr>
      <p>{{ comment.commenter }} ({{ comment.post_time }}) - {{ comment.text }}</p>
      <hr>
    {% endfor %}
  {% endif %}
  </div>
  {% if user.is_authenticated %}
          <p><a href="{% url 'blogpost-comment' blogpost.pk %}">Add a comment</a></p>
        {% else %}
          <p><a href="{% url 'login'%}?next={{request.path}}">Login to add a comment</a></p>
        {% endif %}
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blog Post List</h1>
  {% if blogpost_list %}
  <ul>
    {% for blogpost in blogpost_list %}
      <li>
          <a href="{{ blogpost.get_absolute_url }}">{{ blogpost.title }}</a> ({{ blogpost.post_date }}) - <a href="{{ blogpost.author.get_absolute_url }}">{{blogpost.author}}</a></li>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no blog posts in the library.</p>
  {% endif %}
{% endblock %}

blog/templates/home.html
{% extends "base_generic.html" %}

{% block title %}
<title>DIY Blog Home</title>
{% endblock %}

{% block content %}
  <h1>DIY Blog Home</h1>
  <p>Welcome to DIY Blog, a website developed by <em>mamoore1</em>!</p>
  <h2>Dynamic content</h2>
  <p>The blog has the following post counts:</p>
  <ul>
    <li><strong>Bloggers:</strong> {{ num_bloggers }}</li>
      <li><strong>Blog posts:</strong> {{ num_blogposts }}</li>
      <li><strong>Comments:</strong> {{ num_comments }}</li>
  </ul>

<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}